# Generated by Django 3.2.9 on 2021-11-18 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, default='word', max_length=240)),
                ('spelling_error', models.CharField(db_index=True, default='spelling error', max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='KeyVals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
