# Generated by Django 3.2.9 on 2021-11-18 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spellingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='spelling_error',
            field=models.CharField(db_index=True, default='spellingerror', max_length=240),
        ),
        migrations.AlterField(
            model_name='keyval',
            name='user',
            field=models.ForeignKey(default='...', on_delete=django.db.models.deletion.PROTECT, related_name='KeyVals', to=settings.AUTH_USER_MODEL),
        ),
    ]
