# Generated by Django 3.2.9 on 2021-11-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellingapp', '0002_auto_20211118_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='word',
            field=models.CharField(default='word', max_length=240, null=True),
        ),
    ]
